package pe.com.bibliotecaapp.ViewModel

import pe.com.bibliotecaapp.R
import pe.com.bibliotecaapp.model.Book

object BookService {
    private val books = listOf(
        Book(1, "1984", "George Orwell", 1949, R.drawable.libro1,
            listOf("Dystopian", "Political fiction"), "A dystopian novel set in a totalitarian future."),
        Book(2, "To Kill a Mockingbird", "Harper Lee", 1960, R.drawable.libro2,
            listOf("Southern Gothic", "Bildungsroman"), "A novel about racial injustice in the American South."),
        Book(3, "Pride and Prejudice", "Jane Austen", 1813, R.drawable.libro3,
            listOf("Romance", "Satire"), "A romantic novel that also critiques the British landed gentry."),
        Book(4, "The Great Gatsby", "F. Scott Fitzgerald", 1925, R.drawable.libro4,
            listOf("Tragedy", "Historical"), "A novel about the American dream and the 1920s."),
        Book(5, "Moby-Dick", "Herman Melville", 1851, R.drawable.libro5,
            listOf("Adventure", "Epic"), "A whaling voyage and a man's obsession with a white whale."),
        Book(6, "War and Peace", "Leo Tolstoy", 1869, R.drawable.libro6,
            listOf("Historical", "Philosophical"), "A novel that intertwines the lives of several families during the Napoleonic Wars."),
        Book(7, "The Catcher in the Rye", "J.D. Salinger", 1951, R.drawable.libro7,
            listOf("Young adult", "Realism"), "A story about teenage rebellion and angst."),
        Book(8, "The Hobbit", "J.R.R. Tolkien", 1937, R.drawable.libro4,
            listOf("Fantasy", "Adventure"), "A fantasy novel about the journey of Bilbo Baggins."),
        Book(9, "Crime and Punishment", "Fyodor Dostoevsky", 1866, R.drawable.libro9,
            listOf("Psychological", "Philosophical"), "A novel exploring morality and redemption."),
        Book(10, "The Brothers Karamazov", "Fyodor Dostoevsky", 1880, R.drawable.libro2,
            listOf("Philosophical", "Drama"), "A philosophical novel that delves into faith, doubt, and reason."),
        Book(11, "Jane Eyre", "Charlotte Brontë", 1847, R.drawable.libro11,
            listOf("Romance", "Gothic"), "A novel about the experiences of the titular character, including her growth and love."),
        Book(12, "Brave New World", "Aldous Huxley", 1932, R.drawable.libro12,
            listOf("Dystopian", "Science fiction"), "A dystopian novel set in a future society based on pleasure without moral worries."),
        Book(13, "Wuthering Heights", "Emily Brontë", 1847, R.drawable.libro13,
            listOf("Gothic", "Tragedy"), "A story of passion and revenge set on the Yorkshire moors."),
        Book(14, "Great Expectations", "Charles Dickens", 1861, R.drawable.libro1,
            listOf("Bildungsroman", "Social criticism"), "A novel about the growth and personal development of an orphan named Pip."),
        Book(15, "The Odyssey", "Homer", -800, R.drawable.libro2,
            listOf("Epic", "Mythology"), "An epic poem about the journey of Odysseus back home after the Trojan War."),
        Book(16, "Catch-22", "Joseph Heller", 1961, R.drawable.libro3,
            listOf("Satire", "War"), "A satirical novel about the absurdities of war."),
        Book(17, "The Divine Comedy", "Dante Alighieri", 1320, R.drawable.libro4,
            listOf("Epic", "Religious"), "An epic poem describing Dante's journey through Hell, Purgatory, and Heaven."),
        Book(18, "Frankenstein", "Mary Shelley", 1818, R.drawable.libro6,
            listOf("Gothic", "Science fiction"), "A novel about a scientist who creates a sentient creature."),
        Book(19, "The Iliad", "Homer", -750, R.drawable.libro2,
            listOf("Epic", "Mythology"), "An epic poem about the Trojan War."),
        Book(20, "One Hundred Years of Solitude", "Gabriel Garcia Marquez", 1967, R.drawable.libro4,
            listOf("Magic realism", "Fiction"), "A multi-generational story of the Buendía family."),
        Book(21, "The Grapes of Wrath", "John Steinbeck", 1939, R.drawable.libro13,
            listOf("Realism", "Social criticism"), "A novel about the struggles of a family during the Great Depression."),
        Book(22, "Invisible Man", "Ralph Ellison", 1952, R.drawable.libro13,
            listOf("African American literature", "Social criticism"), "A novel about an African American man's experiences in a racially divided society."),
        Book(23, "Don Quixote", "Miguel de Cervantes", 1605, R.drawable.libro13,
            listOf("Adventure", "Satire"), "A novel about a man who becomes a knight-errant to revive chivalry."),
        Book(24, "The Sun Also Rises", "Ernest Hemingway", 1926, R.drawable.libro13,
            listOf("Modernist", "Fiction"), "A novel about the Lost Generation's experiences in the post-war world."),
        Book(25, "Beloved", "Toni Morrison", 1987, R.drawable.libro13,
            listOf("Historical fiction", "African American literature"), "A novel about the haunting legacy of slavery."),
        Book(26, "Maus", "Art Spiegelman", 1991, R.drawable.libro13,
            listOf("Graphic novel", "Historical"), "A graphic novel depicting the Holocaust through the lens of a father and son."),
        Book(27, "The Sound and the Fury", "William Faulkner", 1929, R.drawable.libro13,
            listOf("Southern Gothic", "Modernist"), "A novel about the decline of a Southern family."),
        Book(28, "Ulysses", "James Joyce", 1922, R.drawable.libro6,
            listOf("Modernist", "Epic"), "A novel that parallels the Odyssey in the context of a single day in Dublin."),
        Book(29, "Slaughterhouse-Five", "Kurt Vonnegut", 1969, R.drawable.libro6,
            listOf("Science fiction", "Satire"), "A novel about the experiences of a soldier during and after World War II."),
        Book(30, "The Stranger", "Albert Camus", 1942, R.drawable.libro6,
            listOf("Philosophical", "Absurdist"), "A novel about an indifferent man who commits murder."),
        Book(31, "Heart of Darkness", "Joseph Conrad", 1899, R.drawable.libro6,
            listOf("Adventure", "Psychological"), "A novella about a voyage up the Congo River and a descent into madness."),
        Book(32, "The Count of Monte Cristo", "Alexandre Dumas", 1844, R.drawable.libro6,
            listOf("Adventure", "Historical"), "A novel about a man who escapes from prison and seeks revenge."),
        Book(33, "Madame Bovary", "Gustave Flaubert", 1857, R.drawable.libro6,
            listOf("Realism", "Tragedy"), "A novel about the adulterous affairs and moral struggles of a doctor's wife."),
        Book(34, "The Picture of Dorian Gray", "Oscar Wilde", 1890, R.drawable.libro5,
            listOf("Philosophical", "Gothic"), "A novel about a man whose portrait ages while he remains young."),
        Book(35, "Anna Karenina", "Leo Tolstoy", 1877, R.drawable.libro5,
            listOf("Realism", "Tragedy"), "A novel about the complexities of love and family in Russian society."),
        Book(36, "The Metamorphosis", "Franz Kafka", 1915, R.drawable.libro5,
            listOf("Absurdist", "Psychological"), "A novella about a man who wakes up one morning to find himself transformed into a giant insect."),
        Book(37, "The Lord of the Rings", "J.R.R. Tolkien", 1954, R.drawable.libro5,
            listOf("Fantasy", "Epic"), "A high-fantasy epic about the quest to destroy a powerful ring."),
        Book(38, "Lolita", "Vladimir Nabokov", 1955, R.drawable.libro5,
            listOf("Psychological", "Controversial"), "A novel about a man's obsession with a young girl."),
        Book(39, "The Catcher in the Rye", "J.D. Salinger", 1951, R.drawable.libro5,
            listOf("Young adult", "Realism"), "A story about teenage rebellion and angst."),
        Book(40, "Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 1997, R.drawable.libro5,
            listOf("Fantasy", "Adventure"), "The first book in a series about a young wizard's adventures at Hogwarts.")
    )

    fun getBooks(): List<Book> = books

    fun getBookById(id: Int): Book? = books.find { it.id == id }
}